coreservice/urls.py
from django.urls import path, include
from unicodedata import name

from coreservice import views
from coreservice.views import *

app_name = 'core'
urlpatterns = [

    path('language/<slug:lang>/activate', views.language_activation, name='switch_language'),

    path('deconnexion', views.user_logout, name='user_logout'),

    path('', HomeView.as_view(), name='home_screen'),

    path('places/', include([

        path('search', PlacesDropDownView.as_view(), name='search_place'),

    ])),

    path('login', LoginView.as_view(), name='login_screen'),
    path('registration', SignUpView.as_view(), name='signup_screen'),
    path('field-validation', CheckExistingFields.as_view(), name='check_existing_fields'),

    path('bookings/', include([

        path('upcoming', UpcomingBookingView.as_view(), name='upcoming_bookings'),
        path('profile', CustomerProfileView.as_view(), name='customer_profile'),

    ])),
    path('account/', include([

        path('profile', CustomerProfileView.as_view(), name='customer_profile'),

        path('notification', EmailMarketingView.as_view(), name='notification'),

        path('password/', include([

            path('password-reset', AskPasswordReset.as_view(), name='ask_password_reset'),

        ])),

        path('payments', include([

            path('', PaymentMethodListView.as_view(), name='payment_information'),
            path('/card-authorization', CardAuthView.as_view(), name="card_authorization"),
            path('/save-payment-method', SavingPaymentMethodView.as_view(), name="saving_payment_method"),
            path("/card/<int:pk>/action", PaymentAction.as_view(), name="card_action"),

        ])),

    ]))

]

sefservices/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oauth/', include('social_django.urls', namespace='social')),

]
urlpatterns += i18n_patterns(
    path('', include('coreservice.urls')),
    prefix_default_language=True,
)

templates/homepage/partials/base_layout.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LuxeRide - Premium Chauffeur Service</title>

    <!-- Bootstrap 5 CSS -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/fonts/inter-webfont/style.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'assets/flags/css/flag-icons.min.css' %}" rel="stylesheet">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'assets/fontawesome/css/brands.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fontawesome/css/solid.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fontawesome/css/duotone.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fontawesome/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fontawesome/css/regular.min.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css"/>
    <!-- Google Fonts -->

    {% block css_extend %}

    {% endblock %}

</head>
<body>
<!-- Navigation -->
{% include 'homepage/partials/header.html' %}

{% block content %}

{% endblock %}

<!-- Footer -->
{% include 'homepage/partials/footer.html' %}

<!-- Login Modal -->
<div class="modal fade" id="loginModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Sign In</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="mb-3">
                        <label class="form-label">Email</label>
                        <input type="email" class="form-control" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Password</label>
                        <input type="password" class="form-control" required>
                    </div>
                    <button type="submit" class="btn btn-luxury w-100">Sign In</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap 5 JS -->
<script src="{% static 'assets/js/bootstrap.bundle.js' %}"></script>
<!-- jQuery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<script src="https://unpkg.com/htmx.org@2.0.4" integrity="sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+" crossorigin="anonymous"></script>

{% block js_extend %}

{% endblock %}
</body>
</html>

templates/homepage/partials/footer.html
<footer class="footer mt-5 ">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 mb-4">
                    <h5>Sef Luxury Services</h5>
                    <p>Premium chauffeur service providing luxury transportation worldwide with professional drivers and exceptional service.</p>
                </div>
                <div class="col-lg-2 col-md-6 mb-4">
                    <h5>Services</h5>
                    <ul class="list-unstyled">
                        <li><a href="#">Airport Transfer</a></li>
                        <li><a href="#">City to City</a></li>
                        <li><a href="#">Hourly Service</a></li>
                        <li><a href="#">VIP Experience</a></li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md-6 mb-4">
                    <h5>Company</h5>
                    <ul class="list-unstyled">
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Careers</a></li>
                        <li><a href="#">Press</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md-6 mb-4">
                    <h5>Support</h5>
                    <ul class="list-unstyled">
                        <li><a href="#">Help Center</a></li>
                        <li><a href="#">Safety</a></li>
                        <li><a href="#">Terms</a></li>
                        <li><a href="#">Privacy</a></li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md-6 mb-4">
                    <h5>Connect</h5>
                    <div class="d-flex gap-3">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                        <a href="#"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
            </div>
            <hr class="my-4">
            <div class="row align-items-center">
                <div class="col-md-6">
                    <p>&copy; 2024 SEF Services. All rights reserved.</p>
                </div>
                <div class="col-md-6 text-md-end">
                    <p>Premium chauffeur service worldwide</p>
                </div>
            </div>
        </div>
    </footer>

templates/homepage/partials/header.html
{% load i18n %}
<nav class="navbar navbar-expand-lg fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'core:home_screen' %}">Sef Luxury Services</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#services">Services</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#about">Help</a>
                </li>

                <li class="nav-item dropdown-center" >
                    {% get_current_language as LANGUAGE_NAME %}
                    {% get_language_info for LANGUAGE_NAME as lang %}
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        {% if LANGUAGE_NAME == "fr" %}
                            <i class="fi fi-fr"></i>
                        {% elif LANGUAGE_NAME == "en" %}
                            <i class="fi fi-us"></i>
                        {% elif LANGUAGE_NAME == "es" %}
                            <i class="fi fi-es"></i>
                        {% endif %}
                        {{ lang.name_translated }}
                    </a>
                    <ul class="dropdown-menu" >
                        {% get_available_languages as LANGUAGES %}
                        {% get_current_language as LANGUAGE_NAME %}
                        {% for LANGUAGE in LANGUAGES %}
                            {% if LANGUAGE.0 != LANGUAGE_NAME %}
                                <li>
                                    <a class="dropdown-item lang_activation"
                                       style="cursor: pointer"
                                       data-activation=" ?next={{ request.path_info }}">
                                        {% if LANGUAGE.0 == "fr" %}
                                            <i class="fi fi-fr"></i>
                                        {% elif LANGUAGE.0 == "en" %}
                                            <i class="fi fi-us"></i>
                                        {% elif LANGUAGE.0 == "es" %}
                                            <i class="fi fi-es"></i>
                                        {% endif %}
                                        <span>{{ LANGUAGE.1 }}</span>
                                    </a>
                                </li>
                            {% endif %}

                        {% endfor %}

                    </ul>

                </li>

                {% if request.user.is_authenticated %}

                    <li class="nav-item dropdown-center">

                        <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fa-regular fa-user"></i> {{ request.user.firstname }}
                        </a>
                        <ul class="dropdown-menu">

                            <li><a class="dropdown-item" href="{% url 'core:upcoming_bookings' %}">{% trans "Bookings" %}</a></li>
                            <li><a class="dropdown-item" href="{% url 'core:customer_profile' %}">{% trans "My Profile" %}</a></li>
                            <li><a class="dropdown-item" href="{% url 'core:user_logout' %}">{% trans "Log Out" %}</a></li>

                        </ul>

                    </li>

                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:login_screen' %}">Sign In</a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

templates/homepage/partials/page_header.html
{% load i18n %}
<nav class="navbar navbar-expand-lg fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'core:home_screen' %}">Sef Luxury Services</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">


                <li class="nav-item dropdown-center" >
                    {% get_current_language as LANGUAGE_NAME %}
                    {% get_language_info for LANGUAGE_NAME as lang %}
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        {% if LANGUAGE_NAME == "fr" %}
                            <i class="fi fi-fr"></i>
                        {% elif LANGUAGE_NAME == "en" %}
                            <i class="fi fi-us"></i>
                        {% elif LANGUAGE_NAME == "es" %}
                            <i class="fi fi-es"></i>
                        {% endif %}
                        {{ lang.name_translated }}
                    </a>
                    <ul class="dropdown-menu" >
                        {% get_available_languages as LANGUAGES %}
                        {% get_current_language as LANGUAGE_NAME %}
                        {% for LANGUAGE in LANGUAGES %}
                            {% if LANGUAGE.0 != LANGUAGE_NAME %}
                                <li>
                                    <a class="dropdown-item lang_activation"
                                       style="cursor: pointer"
                                       data-activation=" ?next={{ request.path_info }}">
                                        {% if LANGUAGE.0 == "fr" %}
                                            <i class="fi fi-fr"></i>
                                        {% elif LANGUAGE.0 == "en" %}
                                            <i class="fi fi-us"></i>
                                        {% elif LANGUAGE.0 == "es" %}
                                            <i class="fi fi-es"></i>
                                        {% endif %}
                                        <span>{{ LANGUAGE.1 }}</span>
                                    </a>
                                </li>
                            {% endif %}

                        {% endfor %}

                    </ul>

                </li>

                {% if request.user.is_authenticated %}

                    <li class="nav-item dropdown-center">

                        <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fa-regular fa-user"></i> {{ request.user.firstname }}
                        </a>
                        <ul class="dropdown-menu">

                            <li><a class="dropdown-item" href="{% url 'core:upcoming_bookings' %}">{% trans "Bookings" %}</a></li>
                            <li><a class="dropdown-item" href="{% url 'core:customer_profile' %}">{% trans "My Profile" %}</a></li>
                            <li><a class="dropdown-item" href="{% url 'core:user_logout' %}">{% trans "Log Out" %}</a></li>

                        </ul>

                    </li>

                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:login_screen' %}">Sign In</a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

templates/homepage/partials/page_layout.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LuxeRide - Premium Chauffeur Service</title>

    <!-- Bootstrap 5 CSS -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/fonts/inter-webfont/style.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'assets/flags/css/flag-icons.min.css' %}" rel="stylesheet">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'assets/fontawesome/css/brands.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fontawesome/css/solid.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fontawesome/css/duotone.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fontawesome/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fontawesome/css/regular.min.css' %}">
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    <!-- Google Fonts -->

    {% block css_extend %}

    {% endblock %}

</head>
<body>
<!-- Navigation -->
{% include 'homepage/partials/page_header.html' %}

{% block content %}

{% endblock %}

{#  Success Alert  #}
<div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div id="successToast"
         class="toast colored-toast bg-success-transparent fade hide" role="alert"
         aria-live="assertive" aria-atomic="true" data-bs-delay="2000">
        <div class="toast-header bg-success text-fixed-white">
            <strong class="me-auto">{% trans 'Success!' %}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="toast"
                    aria-label="Close"></button>
        </div>
        <div class="toast-body">
            Your,toast message here.
        </div>
    </div>
</div>
{#  Success Alert  #}

{#  Error Alert  #}
<div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div id="errorToast"
         class="toast colored-toast bg-primary-transparent fade hide" role="alert"
         aria-live="assertive" aria-atomic="true" data-bs-delay="2000">
        <div class="toast-header bg-primary text-fixed-white">
            <strong class="me-auto">{% trans 'Error!' %}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="toast"
                    aria-label="Close"></button>
        </div>
        <div class="toast-body">
            Your,toast message here.
        </div>
    </div>
</div>
{#  Error Alert  #}

<!-- Footer -->
{% include 'homepage/partials/footer.html' %}


<!-- Bootstrap 5 JS -->
<script src="{% static 'assets/js/bootstrap.bundle.js' %}"></script>
<!-- jQuery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>

{% block js_extend %}

{% endblock %}
</body>
</html>

templates/homepage/partials/partial_places_list.html
{% load i18n %}
{% load static %}

<div class="row bg-white shadow-sm border rounded p-0">
    <div style="height: 185px;overflow-y: auto;" class="p-0">
        <ul class="suggestion-list p-2">
            {% for place in places %}
                <li class="pointer" data-id="{{ place.placeId }}" data-designation="{{ place.mainText }}">
                    <div class="d-flex gap-2 border-bottom border-1 border-dark-subtle py-2 w-100">
                        <div>
                            {% if "hotel" in place.types %}
                                <i class="fa-solid fa-hotel"></i>
                            {% elif "international_airport" in place.types or "airport" in place.types %}
                                <i class="fa-solid fa-plane-up"></i>
                            {% elif "store" in place.types %}
                                <i class="fa-solid fa-building"></i>
                            {% elif "bus_station" in place.types %}
                                <i class="fa-solid fa-bus-simple"></i>
                            {% elif "establishment" in place.types %}
                                <i class="fa-solid fa-building"></i>
                            {% else %}
                                <i class="fa-solid fa-location-dot"></i>
                            {% endif %}
                        </div>
                        <div class="">
                            <h2 class="small p-0 m-0">{{ place.mainText }}</h2>
                            <span style="font-size: smaller" class="p-0 m-0">{{ place.secondaryText }}</span>
                        </div>
                    </div>
                </li>
            {% empty %}
                <li>Aucune information trouvée</li>
            {% endfor %}
        </ul>
    </div>
</div>